Repository bonsai-rx/docs, pull requests merged in 2022-12, with the labels that each got.

#65 Allow code blocks with empty language identifier
  template/styles/main.js
Labels: fix

#29 Add command line interface article
  articles/cli.md
  articles/editor.md
  articles/property-mapping.md
  articles/toc.yml
  images/cli-systemtrayapplication.png
  images/editor-assignvisualizer.png
  images/language-externalizedproperty.png
  images/language-wavplayback-mapping.svg
Labels: article

#67 Simplify inline code block syntax
  articles/cli.md
Labels: fix

#69 Ensure consistent heading level
  articles/expressions-parse.md
Labels: fix

#73 Add extended documentation for property sources
  apidoc/Bonsai_Expressions_BooleanProperty.md
  apidoc/Bonsai_Expressions_ByteProperty.md
  apidoc/Bonsai_Expressions_DateTimeOffsetProperty.md
  apidoc/Bonsai_Expressions_DateTimeProperty.md
  apidoc/Bonsai_Expressions_DoubleProperty.md
  apidoc/Bonsai_Expressions_FloatProperty.md
  apidoc/Bonsai_Expressions_Int64Property.md
  apidoc/Bonsai_Expressions_IntProperty.md
  apidoc/Bonsai_Expressions_PropertySource.md
  apidoc/Bonsai_Expressions_PropertySource_2.md
  apidoc/Bonsai_Expressions_StringProperty.md
  apidoc/Bonsai_Expressions_TimeSpanProperty.md
  apidoc/Bonsai_Expressions_WorkflowProperty.md
  apidoc/Bonsai_Expressions_WorkflowProperty_1.md
  articles/expressions-propertysource.md
Labels: documentation, reference

#76 Add extended documentation for property mapping operators
  apidoc/Bonsai_Expressions_ExternalizedMappingBuilder.md
  apidoc/Bonsai_Expressions_InputMappingBuilder.md
  apidoc/Bonsai_Expressions_PropertyMappingBuilder.md
  articles/expressions-externalizedmapping.md
  articles/expressions-inputmapping.md
  articles/expressions-propertymapping-multiple.md
  articles/expressions-propertymapping.md
  articles/property-mapping.md
Labels: documentation, reference

#79 Add extended documentation for visualizer mapping operator
  apidoc/Bonsai_Expressions_VisualizerMappingBuilder.md
  articles/expressions-visualizermapping.md
Labels: documentation, reference
