Repository bonsai-rx/docs, pull requests merged in 2024-12, with the labels that each got.

#103 Add docfx and documentation style guide
  README.md
  articles/create-package.md
  articles/documentation-docfx.md
  articles/documentation-style-guide.md
  articles/toc.yml
  tutorials/closed-loop.md
Labels: documentation

#105 Remove bootstrapper projects from docfx metadata
  docfx.json
Labels: fix

#109 Flatten table of contents for conceptual documentation
  .config/dotnet-tools.json
  articles/cli.md
  articles/create-package.md
  articles/design-guidelines.md
  articles/editor.md
  articles/environments.md
  articles/gallery.md
  articles/higher-order.md
  articles/installation.md
  articles/observables.md
  articles/operators.md
  articles/packages.md
  articles/property-mapping.md
  articles/scripting-extensions.md
  articles/subjects.md
  articles/toc.yml
  articles/workflow-guidelines.md
Labels: layout, documentation
